GET http://localhost:8088/test/infList?results=成功
Accept: application/json
###
GET http://localhost:8088/test/infList?name=京东
Accept: application/json

###
GET http://localhost:8088/test/infList
Accept: application/json